name: Test and release

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Yarn install
        run: yarn install

      - name: Test
        run: yarn build


  run-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Run tests (Node ${{ matrix.node }})

    steps:
      - uses: actions/checkout@v2
      - name: Configure node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Yarn install
        run: yarn install

      - name: Test
        run: yarn test

  release:
    name: Release
    needs: [run-unit-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure node 14
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Yarn install
        run: yarn install

      - name: Release
        run: yarn release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}





