name: Test and release

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure node 14
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Yarn install
        run: yarn install

      - name: Test
        run: yarn test

  release:
    name: Run Unit Tests
    needs: [run-unit-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure node 14
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Yarn install
        run: yarn install

      - name: Release
        run: yarn release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}





